return {
  BlinkCmpMenu = { bg = "bg.dark", fg = "fg.default" },
  BlinkCmpMenuBorder = { bg = "bg.dark", fg = "bg.dark" },
  BlinkCmpDoc = { bg = "bg.dark", fg = "fg.default" },
  BlinkCmpDocBorder = { bg = "bg.dark", fg = "bg.dark" },
  BlinkCmpSignatureHelp = { bg = "bg.dark", fg = "fg.default" },
  BlinkCmpSignatureHelpBorder = { bg = "bg.dark", fg = "bg.dark" },

  BlinkCmpLabel = { fg = "fg.default" },
  BlinkCmpLabelMatch = { fg = "green.light", bold = true },
  BlinkCmpLabelDetail = { fg = "fg.muted" },
  BlinkCmpLabelDeprecated = { fg = "fg.dim", strikethrough = true },
  BlinkCmpSource = { fg = "fg.muted" },

  BlinkCmpKind = { fg = "fg.default" },
  BlinkCmpKindText = { fg = "fg.default" },
  BlinkCmpKindMethod = { fg = "green.light" },
  BlinkCmpKindFunction = { fg = "green.light" },
  BlinkCmpKindConstructor = { fg = "green.mid" },
  BlinkCmpKindField = { fg = "cyan.base" },
  BlinkCmpKindVariable = { fg = "purple.base" },
  BlinkCmpKindClass = { fg = "green.mid" },
  BlinkCmpKindInterface = { fg = "green.mid" },
  BlinkCmpKindModule = { fg = "blue.base" },
  BlinkCmpKindProperty = { fg = "cyan.base" },
  BlinkCmpKindUnit = { fg = "orange.base" },
  BlinkCmpKindValue = { fg = "orange.base" },
  BlinkCmpKindEnum = { fg = "yellow.base" },
  BlinkCmpKindKeyword = { fg = "green.base" },
  BlinkCmpKindSnippet = { fg = "purple.base" },
  BlinkCmpKindColor = { fg = "cyan.base" },
  BlinkCmpKindFile = { fg = "blue.base" },
  BlinkCmpKindReference = { fg = "cyan.base" },
  BlinkCmpKindFolder = { fg = "blue.base" },
  BlinkCmpKindEnumMember = { fg = "yellow.base" },
  BlinkCmpKindConstant = { fg = "purple.base" },
  BlinkCmpKindStruct = { fg = "green.mid" },
  BlinkCmpKindEvent = { fg = "yellow.base" },
  BlinkCmpKindOperator = { fg = "green.base" },
  BlinkCmpKindTypeParameter = { fg = "green.mid" },

  BlinkCmpGhostText = { fg = "fg.dim" },
  BlinkCmpMenuSelection = { bg = "green.base", fg = "bg.dark", bold = true },
}
