return {
  GitSignsAdd = { fg = "git.add" },
  GitSignsChange = { fg = "git.change" },
  GitSignsDelete = { fg = "orange.base" },
  GitSignsTopdelete = { link = "GitSignsDelete" },
  GitSignsChangedelete = { fg = "orange.base" },
  GitSignsUntracked = { link = "GitSignsAdd" },

  GitSignsAddNr = { fg = "git.add" },
  GitSignsChangeNr = { fg = "git.change" },
  GitSignsDeleteNr = { fg = "orange.base" },
  GitSignsTopdeleteNr = { link = "GitSignsDeleteNr" },
  GitSignsChangedeleteNr = { fg = "orange.base" },
  GitSignsUntrackedNr = { link = "GitSignsAddNr" },

  GitSignsAddLn = { bg = "diff.add" },
  GitSignsChangeLn = { bg = "diff.text" },
  GitSignsDeleteLn = { bg = "bg.focus" },
  GitSignsChangedeleteLn = { bg = "bg.focus" },
  GitSignsUntrackedLn = { link = "GitSignsAddLn" },

  GitSignsAddCul = { link = "GitSignsAdd" },
  GitSignsChangeCul = { link = "GitSignsChange" },
  GitSignsDeleteCul = { link = "GitSignsDelete" },
  GitSignsTopdeleteCul = { link = "GitSignsDeleteCul" },
  GitSignsChangedeleteCul = { link = "GitSignsDeleteCul" },
  GitSignsUntrackedCul = { link = "GitSignsAddCul" },

  GitSignsStagedAdd = { fg = "green.mid" },
  GitSignsStagedChange = { fg = "yellow.base" },
  GitSignsStagedDelete = { fg = "orange.base" },
  GitSignsStagedTopdelete = { link = "GitSignsStagedDelete" },
  GitSignsStagedChangedelete = { fg = "orange.base" },
  GitSignsStagedUntracked = { link = "GitSignsStagedAdd" },

  GitSignsStagedAddNr = { fg = "green.mid" },
  GitSignsStagedChangeNr = { fg = "yellow.base" },
  GitSignsStagedDeleteNr = { fg = "orange.base" },
  GitSignsStagedTopdeleteNr = { link = "GitSignsStagedDeleteNr" },
  GitSignsStagedChangedeleteNr = { fg = "orange.base" },
  GitSignsStagedUntrackedNr = { link = "GitSignsStagedAddNr" },

  GitSignsStagedAddLn = { bg = "diff.add" },
  GitSignsStagedChangeLn = { bg = "diff.text" },
  GitSignsStagedDeleteLn = { bg = "bg.focus" },
  GitSignsStagedChangedeleteLn = { bg = "bg.focus" },
  GitSignsStagedUntrackedLn = { link = "GitSignsStagedAddLn" },

  GitSignsStagedAddCul = { link = "GitSignsStagedAdd" },
  GitSignsStagedChangeCul = { link = "GitSignsStagedChange" },
  GitSignsStagedDeleteCul = { link = "GitSignsStagedDelete" },
  GitSignsStagedTopdeleteCul = { link = "GitSignsStagedDeleteCul" },
  GitSignsStagedChangedeleteCul = { link = "GitSignsStagedDeleteCul" },
  GitSignsStagedUntrackedCul = { link = "GitSignsStagedAddCul" },

  GitSignsAddPreview = { bg = "diff.add" },
  GitSignsDeletePreview = { bg = "bg.focus", fg = "orange.base" },
  GitSignsNoEOLPreview = { fg = "orange.base" },
  GitSignsCurrentLineBlame = { fg = "fg.muted", italic = true },

  GitSignsAddInline = { bg = "diff.add" },
  GitSignsChangeInline = { bg = "diff.text" },
  GitSignsDeleteInline = { bg = "bg.focus", fg = "orange.base" },
  GitSignsAddLnInline = { link = "GitSignsAddInline" },
  GitSignsChangeLnInline = { link = "GitSignsChangeInline" },
  GitSignsDeleteLnInline = { link = "GitSignsDeleteInline" },

  GitSignsDeleteVirtLn = { bg = "bg.focus", fg = "orange.base" },
  GitSignsDeleteVirtLnInLine = { link = "GitSignsDeleteLnInline" },
  GitSignsVirtLnum = { link = "GitSignsDeleteVirtLn" },
}
