return {
  NvimTreeCursorLine = { bg = "green.base", fg = "bg.default" },
  NvimTreeFolderIcon = { fg = "green.base" },
  NvimTreeFolderName = { fg = "green.base" },
  NvimTreeOpenedFolderName = { fg = "green.mid" },
  NvimTreeRootFolder = { fg = "purple.base" },
  NvimTreeWindowPicker = { bg = "green.base", fg = "bg.default" },
  NvimTreeEmptyFolderName = { fg = "green.mid" },
  NvimTreeGitDirty = { fg = "red.base" },
  NvimTreeGitStaged = { fg = "yellow.base" },
  NvimTreeGitMerge = { fg = "cyan.base" },
  NvimTreeGitRenamed = { fg = "yellow.base" },
  NvimTreeGitNew = { fg = "green.light" },
  NvimTreeGitDeleted = { fg = "red.base" },
}
