return {
  ["@keyword.markdown"] = { fg = "green.base" },
  ["@markup.list.markdown"] = { fg = "green.soft" },
  ["@markup.heading.1.markdown"] = { fg = "green.base" },
  ["@markup.heading.2.markdown"] = { fg = "green.mid" },
  ["@markup.heading.3.markdown"] = { fg = "purple.base" },
  ["@markup.heading.4.markdown"] = { fg = "cyan.base" },
  ["@markup.heading.5.markdown"] = { fg = "blue.base" },
  ["@markup.heading.6.markdown"] = { fg = "orange.base" },
  markdownH1 = { fg = "green.base", bg = "NONE" },
  markdownH2 = { fg = "green.mid", bg = "NONE" },
  markdownH3 = { fg = "purple.base", bg = "NONE" },
  markdownH4 = { fg = "cyan.base", bg = "NONE" },
  markdownH5 = { fg = "blue.base", bg = "NONE" },
  markdownH6 = { fg = "orange.base", bg = "NONE" },
  markdownHeadingDelimiter = { fg = "fg.muted", bg = "NONE" },
  ["@markup.quote.markdown"] = { fg = "green.soft" },
  ["@markup.raw.block.markdown"] = { fg = "purple.base", bg = "NONE" },
  markdownCode = { fg = "purple.base", bg = "NONE" },
  markdownCodeBlock = { fg = "purple.base", bg = "NONE" },
  markdownCodeDelimiter = { fg = "fg.muted", bg = "NONE" },
  ["@markup.raw.delimiter.markdown"] = { fg = "fg.muted" },
  ["@markup.raw.markdown_inline"] = { fg = "green.mid" },
  ["@punctuation.special.markdown"] = { fg = "fg.muted" },
}
