return {
  ["@conditional.python"] = { fg = "green.base" },
  ["@constant.builtin.python"] = { fg = "cyan.base" },
  ["@include.python"] = { fg = "green.base" },
  ["@keyword.function.python"] = { fg = "green.base" },
  ["@keyword.python"] = { fg = "green.base" },
  ["@lsp.mod.definition.python"] = { fg = "green.light" },
  ["@lsp.type.class.python"] = { fg = "green.mid" },
  ["@lsp.type.variable.python"] = { fg = "purple.base" },
  ["@lsp.typemod.class.definition.python"] = { fg = "green.mid" },
  ["@lsp.typemod.method.definition.python"] = { fg = "green.light" },
  ["@lsp.typemod.parameter.definition.python"] = { fg = "purple.base" },
  ["@method.call.python"] = { fg = "green.light" },
  ["@module.python"] = { fg = "fg.default" },
  ["@operator.python"] = { fg = "green.base" },
  ["@parameter.python"] = { fg = "purple.base" },
  ["@punctuation.bracket.python"] = { fg = "green.base" },
  ["@variable.builtin.python"] = { fg = "purple.base" },
  ["@variable.python"] = { fg = "purple.base" },
  ["@variable.parameter.python"] = { fg = "cyan.base" },
}
