return {
  ["@function.call.typescript"] = { fg = "green.light" },
  ["@function.typescript"] = { fg = "green.light" },
  ["@keyword.typescript"] = { link = "@keyword" },
  ["@lsp.mod.defaultLibrary.typescript"] = { fg = "purple.base" },
  ["@lsp.mod.readonly.typescript"] = { fg = "purple.base" },
  ["@lsp.type.enum.typescript"] = { fg = "green.mid" },
  ["@lsp.type.interface.typescript"] = { fg = "green.mid" },
  ["@lsp.typemod.class.defaultLibrary.typescript"] = { fg = "cyan.base" },
  ["@lsp.typemod.function.readonly.typescript"] = { fg = "green.light" },
  ["@lsp.typemod.interface.defaultLibrary.typescript"] = { fg = "cyan.base" },
  ["@lsp.typemod.enumMember.declaration.typescript"] = { fg = "green.light" },
  ["@lsp.typemod.enumMember.readonly.typescript"] = { fg = "purple.base" },
  ["@lsp.typemod.member.defaultLibrary.typescript"] = { fg = "green.light" },
  ["@lsp.typemod.property.declaration.typescript"] = { fg = "green.light" },
  ["@method.call.typescript"] = { fg = "green.light" },
  ["@method.typescript"] = { fg = "green.light" },
  ["@operator.typescript"] = { fg = "green.base" },
  ["@parameter.typescript"] = { fg = "purple.base" },
  ["@punctuation.bracket.typescript"] = { fg = "green.base" },
  ["@type.builtin.typescript"] = { fg = "purple.base" },
  ["@type.typescript"] = { fg = "green.mid" },
  ["@variable.builtin.typescript"] = { fg = "purple.base" },
  ["@variable.typescript"] = { fg = "purple.base" },
}
