return {
  ColorColumn = { bg = "bg.default" },
  Conceal = { fg = "fg.muted" },
  CurSearch = { fg = "bg.dark", bg = "yellow.base" },
  CursorColumn = { fg = "fg.muted", bg = "bg.default" },
  CursorLine = { bg = "bg.focus" },
  CursorLineFold = { fg = "fg.muted", bg = "bg.focus" },
  CursorLineNr = { fg = "fg.default", bg = "bg.focus" },
  CursorLineSign = { fg = "fg.muted", bg = "bg.default" },
  EndOfBuffer = { fg = "bg.default", bg = "bg.default" },
  FloatBorder = { fg = "bg.dark", bg = "bg.dark" },
  FloatFooter = { fg = "bg.dark", bg = "bg.dark" },
  FloatTitle = { fg = "fg.default", bg = "bg.dark" },
  FoldColumn = { fg = "fg.muted", bg = "bg.default" },
  Folded = { fg = "fg.muted", bg = "bg.dark" },
  IncSearch = { fg = "orange.base", bg = "bg.selected" },
  LineNr = { fg = "fg.dim", bg = "bg.default" },
  LineNrAbove = { fg = "fg.dim", bg = "bg.default" },
  LineNrBelow = { fg = "fg.dim", bg = "bg.default" },
  NonText = { fg = "fg.muted" },
  Normal = { fg = "fg.default", bg = "bg.default" },
  NormalFloat = { fg = "fg.default", bg = "bg.dark" },
  NormalNC = { fg = "fg.default", bg = "bg.default" },
  NormalSB = { fg = "fg.default", bg = "bg.focus" },
  Pmenu = { fg = "fg.default", bg = "bg.dark" },
  PmenuExtra = { fg = "fg.muted", bg = "bg.dark" },
  PmenuExtraSel = { fg = "fg.default", bg = "bg.dark" },
  PmenuKind = { fg = "fg.muted", bg = "bg.dark" },
  PmenuKindSel = { fg = "fg.default", bg = "bg.dark" },
  PmenuSbar = { bg = "bg.dark" },
  PmenuSel = { fg = "fg.default", bg = "bg.dark" },
  PmenuThumb = { bg = "fg.muted" },
  Search = { fg = "yellow.base", bg = "bg.dark" },
  SignColumn = { fg = "fg.muted", bg = "bg.default" },
  StatusLine = { fg = "fg.default", bg = "bg.default" },
  StatusLineNC = { fg = "fg.muted", bg = "bg.default" },
  StatusLineTerm = { fg = "fg.default", bg = "bg.focus" },
  StatusLineTermNC = { fg = "fg.muted", bg = "bg.dark" },
  TabLine = { fg = "green.base", bg = "bg.default" },
  TabLineFill = { bg = "bg.default" },
  TabLineSel = { fg = "bg.dark", bg = "green.base" },
  VertSplit = { fg = "bg.dark", bg = "bg.default" },
  Visual = { bg = "bg.selected" },
  VisualNOS = { bg = "bg.selected" },
  WinBar = { fg = "fg.default", bg = "bg.default" },
  WinBarNC = { fg = "fg.muted", bg = "bg.dark" },
  WinSeparator = { fg = "bg.dark", bg = "bg.default" },
}
