return {
  ColorColumn = { bg = "bg.default" },
  Conceal = { fg = "fg.muted" },
  CurSearch = { fg = "bg.dark", bg = "yellow.base" },
  Directory = { fg = "blue.base" },
  CursorColumn = { fg = "fg.muted", bg = "bg.default" },
  CursorLine = { bg = "bg.focus" },
  CursorLineFold = { fg = "fg.muted", bg = "bg.focus" },
  CursorLineNr = { fg = "fg.default", bg = "bg.focus" },
  CursorLineSign = { fg = "fg.muted", bg = "bg.default" },
  EndOfBuffer = { fg = "bg.default", bg = "bg.default" },
  ErrorMsg = { fg = "red.base" },
  FloatBorder = { fg = "bg.dark", bg = "bg.dark" },
  FloatFooter = { fg = "bg.dark", bg = "bg.dark" },
  FloatShadow = { bg = "bg.dark" },
  FloatShadowThrough = { bg = "bg.dark" },
  FloatTitle = { fg = "fg.default", bg = "bg.dark" },
  FoldColumn = { fg = "fg.muted" },
  Folded = { fg = "fg.muted", bg = "bg.dark" },
  IncSearch = { fg = "orange.base", bg = "bg.selected" },
  MatchParen = { fg = "cyan.base", bg = "bg.default" },
  ModeMsg = { fg = "fg.default", bg = "bg.default" },
  MoreMsg = { fg = "green.mid" },
  MsgArea = { fg = "fg.default", bg = "bg.default" },
  MsgSeparator = { fg = "fg.default", bg = "bg.default" },
  LineNr = { fg = "fg.dim", bg = "NONE" },
  LineNrAbove = { fg = "fg.dim", bg = "NONE" },
  LineNrBelow = { fg = "fg.dim", bg = "NONE" },
  NonText = { fg = "fg.muted" },
  Normal = { fg = "fg.default", bg = "bg.default" },
  NormalFloat = { fg = "fg.default", bg = "bg.dark" },
  NormalFloatNC = { fg = "fg.default", bg = "bg.dark" },
  NormalNC = { fg = "fg.default", bg = "bg.default" },
  NormalSB = { fg = "fg.default", bg = "bg.focus" },
  Pmenu = { fg = "fg.default", bg = "bg.dark" },
  PmenuExtra = { fg = "fg.muted", bg = "bg.dark" },
  PmenuExtraSel = { fg = "fg.default", bg = "bg.dark" },
  PmenuKind = { fg = "fg.muted", bg = "bg.dark" },
  PmenuKindSel = { fg = "fg.default", bg = "bg.dark" },
  PmenuSbar = { bg = "bg.dark" },
  PmenuSel = { fg = "fg.default", bg = "bg.dark" },
  PmenuThumb = { bg = "fg.muted" },
  Question = { fg = "green.light", bg = "bg.default" },
  Search = { fg = "yellow.base", bg = "bg.dark" },
  SignColumn = { fg = "fg.muted", bg = "NONE" },
  Special = { fg = "green.base" },
  SpecialKey = { fg = "fg.dim" },
  StatusLine = { fg = "fg.default", bg = "bg.default" },
  StatusLineNC = { fg = "fg.muted", bg = "bg.default" },
  StatusLineTerm = { fg = "fg.default", bg = "bg.focus" },
  StatusLineTermNC = { fg = "fg.muted", bg = "bg.dark" },
  Substitute = { fg = "yellow.base", bg = "bg.selected" },
  TermCursor = { fg = "bg.default", bg = "green.mid" },
  TermCursorNC = { fg = "bg.default", bg = "fg.muted" },
  TabLine = { fg = "green.base", bg = "bg.default" },
  TabLineFill = { bg = "bg.default" },
  TabLineSel = { fg = "bg.dark", bg = "green.base" },
  Title = { fg = "green.base" },
  VertSplit = { fg = "bg.dark", bg = "bg.default" },
  Visual = { bg = "bg.selected" },
  VisualNOS = { bg = "bg.selected" },
  WarningMsg = { fg = "yellow.base" },
  Whitespace = { fg = "fg.dim" },
  WildMenu = { fg = "bg.dark", bg = "blue.base" },
  WinBar = { fg = "fg.default", bg = "bg.default" },
  WinBarNC = { fg = "fg.muted", bg = "bg.dark" },
  WinSeparator = { fg = "bg.dark", bg = "bg.default" },
}
