return {
  DiagnosticError = { fg = "diagnostic.error" },
  DiagnosticFloatingError = { fg = "diagnostic.error" },
  DiagnosticFloatingHint = { fg = "diagnostic.hint" },
  DiagnosticFloatingInfo = { fg = "diagnostic.info" },
  DiagnosticFloatingWarn = { fg = "diagnostic.warn" },
  DiagnosticHint = { fg = "diagnostic.hint" },
  DiagnosticInfo = { fg = "diagnostic.info" },
  DiagnosticSignError = { fg = "diagnostic.error" },
  DiagnosticSignHint = { fg = "diagnostic.hint" },
  DiagnosticSignInfo = { fg = "diagnostic.info" },
  DiagnosticSignWarn = { fg = "diagnostic.warn" },
  DiagnosticUnderlineError = { sp = "diagnostic.error", undercurl = true },
  DiagnosticUnderlineHint = { sp = "diagnostic.hint", undercurl = true },
  DiagnosticUnderlineInfo = { sp = "diagnostic.info", undercurl = true },
  DiagnosticUnderlineWarn = { sp = "diagnostic.warn", undercurl = true },
  DiagnosticVirtualTextError = { fg = "virtual_text.error" },
  DiagnosticVirtualTextHint = { fg = "virtual_text.hint" },
  DiagnosticVirtualTextInfo = { fg = "virtual_text.info" },
  DiagnosticVirtualTextWarn = { fg = "virtual_text.warn" },
  DiagnosticWarn = { fg = "diagnostic.warn" },
  SpellBad = { link = "DiagnosticUnderlineError" },
  SpellCap = { link = "DiagnosticUnderlineWarn" },
  SpellLocal = { link = "DiagnosticUnderlineWarn" },
  SpellRare = { link = "DiagnosticUnderlineWarn" },
}
