return {
  ["@lsp.type.class"] = { fg = "green.mid" },
  ["@lsp.type.enumMember"] = { fg = "purple.base" },
  ["@lsp.type.error"] = { fg = "diagnostic.error" },
  ["@lsp.type.function"] = { fg = "green.light" },
  ["@lsp.type.hint"] = { fg = "diagnostic.hint" },
  ["@lsp.type.information"] = { fg = "diagnostic.info" },
  ["@lsp.type.interface"] = { fg = "green.mid" },
  ["@lsp.type.keyword"] = { fg = "green.base" },
  ["@lsp.type.member"] = { fg = "cyan.base" },
  ["@lsp.type.method"] = { fg = "green.light" },
  ["@lsp.type.parameter"] = { fg = "purple.base" },
  ["@lsp.type.property"] = { fg = "cyan.base" },
  ["@lsp.type.type"] = { fg = "green.mid" },
  ["@lsp.type.variable"] = { fg = "purple.base" },
  ["@lsp.type.warning"] = { fg = "diagnostic.warn" },
  ["@lsp.typemod.function.defaultLibrary"] = { fg = "green.mid" },
  ["@lsp.typemod.property.readonly"] = { fg = "purple.base" },
  ["@lsp.typemod.variable.defaultLibrary"] = { fg = "purple.base" },
  ["@lsp.typemod.variable.readonly"] = { fg = "purple.base" },
}
